name: Expression Practice

on:
  push:

jobs:
  status-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Success
        run: echo "Step 1 - SUCCESS"

      - name: Step 2 - success()
        if: ${{ success() }}
        run: echo "Step 2 - success() is TRUE"

      - name: Step 3 - Failure
        run: exit 1

      - name: Step 4 - success()
        if: ${{ success() }}
        run: echo "Step 4 - success() is TRUE"

      - name: Step 5 - failure()
        if: ${{ failure() }}
        run: echo "Step 5 - failure() is TRUE"

      - name: Step 6 - always()
        if: ${{ always() }}
        run: echo "Step 6 - always() is TRUE"

      - name: Step 7 - cancelled()
        if: ${{ cancelled() }}
        run: echo "Step 7 - cancelled() is TRUE"
