name: Expression Practice

on:
  push:

jobs:
  conditions:
    runs-on: ubuntu-latest

    steps:
      - name: Check master AND push
        if: ${{ github.ref_name == 'master' && github.event_name == 'push' }}
        run: echo "Step 6 - We are on master AND workflow was triggered by push"

      - name: Check master OR develop
        if: ${{ github.ref_name == 'master' || github.ref_name == 'develop' }}
        run: echo "Step 7 - We are on master OR develop"

      - name: Check develop AND push
        if: ${{ github.ref_name == 'develop' && github.event_name == 'push' }}
        run: echo "Step 8 - We are on develop AND workflow was triggered by push"
